 ### * sklearn 라이브러리에서 간단한 분류 모델에 관련하여 SVM과 KNN 이 있다

 KNN (K-Nearest Neighbors) : 최근접 분류기
	새로운 데이터가 들어오면 훈련데이타 중에서 가장 가까운 데이터 K개를 찾는다.
	이 중에서 빈도가 높은 label(결과)을 새 데이터의 레이블로 예측한다. 
		- fit() : 학습기계에 데이터를 학습시키는 메소드
		- predict() : 데이터를 넣고 예측하는 메소드
		- score() : 정확도 측정

svm(서포트벡터머신:분류, 회귀) 알고리즘 : 분류(SVC), 회귀(SVR)
		- fit() : 학습기계에 데이터를 학습시키는 메소드
		- predict() : 데이터를 넣고 예측하는 메소드
		- metrics.accuracy_score() : 정확도 측정 (검증)



### * 절차

(1) 데이타 읽어오기

(2) 데이터와 레이블 분리 변수 선언

(3) 훈련데이터와 테스트 데이터로 분리하기

(4) 모델로 학습하기

(5) 예측하기

(6) 검증하기

(7) 정확도 측정하기

In [77]:
# (1) 데이타 읽어오기

import numpy as np
from sklearn import datasets

iris = datasets.load_iris()


In [26]:
# (2) 데이터와 레이블 분리 변수 선언 ( 이미 데이터와 레이블이 정해짐 )
X=iris['data']
y=iris['target'] # 답(레이블)이라고 부름


In [65]:
# (3) 훈련데이터와 테스트 데이터로 분리하기
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X,y, test_size=0.7) # 기본값 학습데이타8: 검증데이타2
X_train # head()는 df에서만 사용 가능


print(X_train[:10]) # 훈련데이터(학습할 데이터)
print(X_test[:10])  # 검증데이터
print(y_train[:10]) # 훈련답(학습에 대한 답)
print(y_test[:10])  # 검증데이타의 답


[[6.1 3.  4.6 1.4]
 [7.7 2.8 6.7 2. ]
 [6.  2.7 5.1 1.6]
 [6.9 3.1 5.4 2.1]
 [6.2 2.9 4.3 1.3]
 [7.7 3.8 6.7 2.2]
 [6.9 3.2 5.7 2.3]
 [5.6 3.  4.1 1.3]
 [6.7 3.3 5.7 2.5]
 [5.4 3.9 1.3 0.4]]
[[5.6 2.8 4.9 2. ]
 [5.8 2.6 4.  1.2]
 [5.  3.4 1.6 0.4]
 [5.5 3.5 1.3 0.2]
 [6.5 3.  5.2 2. ]
 [6.5 3.2 5.1 2. ]
 [4.9 3.  1.4 0.2]
 [7.7 2.6 6.9 2.3]
 [5.8 2.8 5.1 2.4]
 [6.3 2.7 4.9 1.8]]
[1 2 1 2 1 2 2 1 2 0]
[2 1 0 0 2 2 0 2 2 2]


In [66]:
# (4) 모델에 데이터를 학습하기
# 훈련데이타와 훈련레이블를 인자로 넣어 학습한 결과 knn 객체를 리턴한다
# n_neighbors : 이웃갯수 지정

from sklearn.neighbors import KNeighborsClassifier

knn = KNeighborsClassifier()

knn.fit(X_train, y_train) # 지도학습(답과 학습을 같이 줌)


KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
                     metric_params=None, n_jobs=None, n_neighbors=5, p=2,
                     weights='uniform')

In [67]:
# (5) 새로운 샘플 데이타가 들어왔을 때 label 예측하기
# 너무 동떨어진 데이타 입력하면 결과 예측 성능이 낮기에 기존 샘플과 유사하게 만듬
newData = np.array([[8.5, 5.5, 5., 0.3]]) 

prediction = knn.predict(newData)
prediction # array([0]) = setosa
iris['target_names'][prediction]




array(['virginica'], dtype='<U10')

In [68]:
# (6) 검증하기
# 실제 레이블과 예측값의 정확도 확인

knn.score(X_test, y_test)


0.9047619047619048

In [69]:
# (7) 정확도 측정 : mean() 함수 이용

"""
a = np.array([1,2,3,4])
b = np.array([1,2,3,5])
print(a==b)
print(np.mean(a==b)) # True=1, False=0 의 평균
"""
# X_tets: 전체 데이타 중에서 검증하기 위해 검증하기 위해서 20% 데이타
# y_test: 20% 검증데이타의 답

y_predict = knn.predict(X_test)
from sklearn import metrics

ac_score = metrics.accuracy_score(y_test, y_predict)
ac_score


0.9047619047619048